server:
  port: 9000

spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: DOT_COMMU
    password: password
    sqlScriptEncoding: UTF-8
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
security:
  basic:
    enabled: false
